# Generated by Django 5.0.14 on 2025-11-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="Nombre")),
                (
                    "clave",
                    models.CharField(max_length=10, unique=True, verbose_name="Clave"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "apellido_paterno",
                    models.CharField(max_length=100, verbose_name="Apellido paterno"),
                ),
                (
                    "apellido_materno",
                    models.CharField(max_length=100, verbose_name="Apellido materno"),
                ),
                (
                    "matricula",
                    models.CharField(
                        help_text="Identificador único de alumno",
                        max_length=20,
                        unique=True,
                        verbose_name="Matrícula",
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("telefono", models.CharField(max_length=15, verbose_name="Teléfono")),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                ("grupo", models.CharField(max_length=10, verbose_name="Grupo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Inscrito", "Inscrito"),
                            ("Baja temporal", "Baja temporal"),
                            ("Baja definitiva", "Baja definitiva"),
                            ("Egresado", "Egresado"),
                        ],
                        default="Inscrito",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_inscripcion",
                    models.DateField(verbose_name="Fecha de inscripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado"),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="students.career",
                        verbose_name="Carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "ordering": ["apellido_paterno", "apellido_materno", "nombre"],
            },
        ),
    ]
